import { createElement } from '@lwc/engine-dom';
import CustomSLDS1Inhibit from 'c/customSLDS1Inhibit';

describe('c-custom-s-l-d-s-1-inhibit', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-custom-s-l-d-s-1-inhibit', {
            is: CustomSLDS1Inhibit
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});